//
//  protoc-gen-fieldmeta-swift
//
//  A pure-Swift protoc plugin that emits FieldMetadataRegistry.swift for
//  (meshtastic.field_metadata) options — the Swift-native sibling of the Go
//  protoc-gen-fieldmeta in ../protoc-gen-fieldmeta, for consumers whose
//  toolchain is already swift-protobuf based (e.g. Meshtastic-Apple).
//  Output is byte-identical to the Go plugin's swift target.
//
//  Built on SwiftProtobufPluginLibrary — the same library protoc-gen-swift itself
//  uses — so Swift type paths (`Config.PositionConfig`) and property names
//  (`rxGpio`) match the real generated code BY CONSTRUCTION (same NamingUtils),
//  rather than by reimplementing snake_case→camelCase and hoping it agrees.
//

import Foundation
import SwiftProtobuf
import SwiftProtobufPluginLibrary

@main
struct FieldMetaSwiftGenerator: CodeGenerator {

    var supportedFeatures: [Google_Protobuf_Compiler_CodeGeneratorResponse.Feature] {
        [.proto3Optional]
    }

    // Registering the extension here is what makes `field.options.fieldMetadata`
    // decode as a typed value instead of landing in unknownFields.
    var customOptionExtensions: [any AnyMessageExtension] { [Extensions_field_metadata] }

    var version: String? { "1.0.0 (swift)" }

    struct Entry {
        let swiftTypePath: String     // e.g. Config.PositionConfig
        let protoTypeName: String     // e.g. meshtastic.Config.PositionConfig
        let swiftFieldName: String    // e.g. rxGpio
        let protoFieldName: String    // e.g. rx_gpio (ordering key, matches the Go plugin)
        let tag: Int32
        let metadata: FieldMetadata
        // Mirrored from the field's standard `[deprecated = true]` option (not
        // from the custom annotation); surfaced as the `deprecated` attribute.
        let deprecated: Bool
    }

    func generate(
        files: [FileDescriptor],
        parameter: any CodeGeneratorParameter,
        protoCompilerContext: any ProtoCompilerContext,
        generatorOutputs: any GeneratorOutputs
    ) throws {
        // Locate the FieldMetadata message descriptor (drives the emitted struct's
        // shape, so a schema-only attribute addition needs no plugin change).
        var metadataDescriptor: Descriptor?
        for file in files {
            if let d = file.messages.first(where: { $0.fullName == "meshtastic.FieldMetadata" }) {
                metadataDescriptor = d
                break
            }
        }
        guard let metadataDescriptor else {
            throw GenError.message("meshtastic.FieldMetadata not found among the input protos — include meshtastic/field_metadata.proto")
        }
        // Scalar-only guard, mirroring the Go plugin's hard error.
        for f in metadataDescriptor.fields {
            guard swiftScalarType(for: f.type) != nil, !f.isRepeated else {
                throw GenError.message("FieldMetadata.\(f.name): attributes must be scalar (bool/int/float/string), not repeated/message/enum/bytes")
            }
        }

        var entries: [Entry] = []
        for file in files {
            let namer = SwiftProtobufNamer()
            var stack = file.messages
            while !stack.isEmpty {
                let message = stack.removeFirst()
                stack.append(contentsOf: message.messages)
                // A field earns an entry if it carries the custom annotation OR
                // the standard `deprecated` option (which we mirror below).
                for field in message.fields where field.options.hasFieldMetadata || field.options.deprecated {
                    entries.append(Entry(
                        swiftTypePath: namer.fullName(message: message),
                        protoTypeName: message.fullName,
                        swiftFieldName: namer.messagePropertyNames(field: field, prefixed: "", includeHasAndClear: false).name,
                        protoFieldName: field.name,
                        tag: field.number,
                        metadata: field.options.fieldMetadata,
                        deprecated: field.options.deprecated
                    ))
                }
            }
        }

        var out = "// DO NOT EDIT -- generated by protoc-gen-fieldmeta from (meshtastic.field_metadata) options.\n\n"

        // The FieldMetadata struct, shaped by the schema.
        out += "public struct FieldMetadata {\n"
        for f in metadataDescriptor.fields {
            out += "    public var \(NamingUtils.toLowerCamelCase(f.name)): \(swiftScalarType(for: f.type)!)? = nil\n"
        }
        out += "}\n\n"

        // Typed accessors as extensions on the real swift-protobuf message types.
        // Ordering mirrors the Go plugin (so the two stay byte-identical): groups
        // by proto type path sorted alphabetically, fields within a group sorted
        // by proto field name.
        var grouped: [String: [Entry]] = [:]
        for e in entries {
            grouped[e.swiftTypePath, default: []].append(e)
        }
        for typePath in grouped.keys.sorted() {
            out += "extension \(typePath) {\n"
            for e in grouped[typePath]!.sorted(by: { $0.protoFieldName < $1.protoFieldName }) {
                out += "    public static var \(e.swiftFieldName): FieldMetadata { \(literal(for: e, shape: metadataDescriptor)) }\n"
            }
            out += "}\n\n"
        }

        // Low-level table + dynamic lookup. Entries sorted by (proto type, tag),
        // matching the Go plugin.
        out += "public enum FieldMetadataRegistry {\n"
        out += "    // Keyed by \"\\(messageType)#\\(tag)\".\n"
        out += "    static let registry: [String: FieldMetadata] = [\n"
        let sortedEntries = entries.sorted { a, b in
            a.protoTypeName != b.protoTypeName ? a.protoTypeName < b.protoTypeName : a.tag < b.tag
        }
        for e in sortedEntries {
            out += "        \"\(e.protoTypeName)#\(e.tag)\": \(literal(for: e, shape: metadataDescriptor)),\n"
        }
        out += "    ]\n\n"
        out += "    /// Metadata for the field with `tag` on `messageType`, or nil.\n"
        out += "    public static func get(_ messageType: String, tag: Int) -> FieldMetadata? {\n"
        out += "        return registry[\"\\(messageType)#\\(tag)\"]\n"
        out += "    }\n"
        out += "}\n"

        try generatorOutputs.add(fileName: "FieldMetadataRegistry.swift", contents: out)
    }

    /// FieldMetadata(...) literal with only the explicitly-set attributes.
    ///
    /// Args are sorted by proto (snake_case) field name, matching the Go
    /// plugin's ordering so the two stay byte-identical even when a field
    /// carries more than one attribute. `deprecated` is sourced from the entry's
    /// mirrored standard option, not from the custom-annotation `metadata`.
    private func literal(for entry: Entry, shape: Descriptor) -> String {
        let metadata = entry.metadata
        var args: [(name: String, rendered: String)] = []
        for f in shape.fields {
            let label = NamingUtils.toLowerCamelCase(f.name)
            switch f.name {
            case "diy_only":   if metadata.hasDiyOnly { args.append((f.name, "\(label): \(metadata.diyOnly)")) }
            case "admin_only": if metadata.hasAdminOnly { args.append((f.name, "\(label): \(metadata.adminOnly)")) }
            case "min_value":  if metadata.hasMinValue { args.append((f.name, "\(label): \(metadata.minValue)")) }
            case "max_value":  if metadata.hasMaxValue { args.append((f.name, "\(label): \(metadata.maxValue)")) }
            case "unit":       if metadata.hasUnit { args.append((f.name, "\(label): \(swiftStringLiteral(metadata.unit))")) }
            case "deprecated": if entry.deprecated { args.append((f.name, "\(label): true")) }
            default:
                // A new schema attribute reached emission without plugin support — fail loudly
                // rather than silently dropping metadata (parity with the Go plugin's guard).
                fatalError("FieldMetadata attribute '\(f.name)' is not handled by protoc-gen-fieldmeta-swift; add a case")
            }
        }
        let rendered = args.sorted { $0.name < $1.name }.map(\.rendered)
        return "FieldMetadata(\(rendered.joined(separator: ", ")))"
    }

    private func swiftScalarType(for type: Google_Protobuf_FieldDescriptorProto.TypeEnum) -> String? {
        switch type {
        case .bool: return "Bool"
        case .double: return "Double"
        case .float: return "Float"
        case .string: return "String"
        case .int32, .sint32, .sfixed32: return "Int32"
        case .uint32, .fixed32: return "UInt32"
        case .int64, .sint64, .sfixed64: return "Int64"
        case .uint64, .fixed64: return "UInt64"
        default: return nil
        }
    }

    private func swiftStringLiteral(_ s: String) -> String {
        var escaped = ""
        for c in s.unicodeScalars {
            switch c {
            case "\"": escaped += "\\\""
            case "\\": escaped += "\\\\"
            case "\n": escaped += "\\n"
            default: escaped.unicodeScalars.append(c)
            }
        }
        return "\"\(escaped)\""
    }

    enum GenError: Error, CustomStringConvertible {
        case message(String)
        var description: String {
            switch self { case .message(let m): return m }
        }
    }
}
