package main

import (
	"fmt"
	"sort"
	"strconv"
	"strings"

	"google.golang.org/protobuf/reflect/protoreflect"
)

const doNotEdit = "DO NOT EDIT -- generated by protoc-gen-fieldmeta from (meshtastic.field_metadata) options."

// ---- shared helpers -------------------------------------------------------

func quoteString(s string) string {
	var b strings.Builder
	b.WriteByte('"')
	for _, r := range s {
		switch r {
		case '\\':
			b.WriteString(`\\`)
		case '"':
			b.WriteString(`\"`)
		case '\n':
			b.WriteString(`\n`)
		case '\t':
			b.WriteString(`\t`)
		default:
			b.WriteRune(r)
		}
	}
	b.WriteByte('"')
	return b.String()
}

// decimalFloat renders a float64 with a guaranteed decimal point so it is a
// valid floating-point literal in languages that won't coerce an integer
// literal to a float (Rust, Swift, Kotlin).
func decimalFloat(f float64) string {
	s := strconv.FormatFloat(f, 'f', -1, 64)
	if !strings.ContainsAny(s, ".eE") {
		s += ".0"
	}
	return s
}

func snakeToCamel(s string) string {
	parts := strings.Split(s, "_")
	for i := 1; i < len(parts); i++ {
		if parts[i] != "" {
			parts[i] = strings.ToUpper(parts[i][:1]) + parts[i][1:]
		}
	}
	return strings.Join(parts, "")
}

// pascalToSnake lowercases a proto message name for use as a Rust module name
// ("PositionConfig" -> "position_config").
func pascalToSnake(s string) string {
	var b strings.Builder
	for i, r := range s {
		if r >= 'A' && r <= 'Z' {
			if i > 0 {
				b.WriteByte('_')
			}
			b.WriteRune(r - 'A' + 'a')
		} else {
			b.WriteRune(r)
		}
	}
	return b.String()
}

// fieldValue returns the metaField set for name on this entry, if present.
func (e entry) fieldValue(name string) (metaField, bool) {
	for _, f := range e.Fields {
		if f.Name == name {
			return f, true
		}
	}
	return metaField{}, false
}

// ---- accessor tree --------------------------------------------------------

// metaTree mirrors the proto message nesting so each target can emit
// namespaced, name-based accessors (Config.PositionConfig.rxGpio) instead of
// requiring callers to know magic message-name strings and field tags.
type metaTree struct {
	children map[string]*metaTree
	fields   []entry
}

func buildTree(entries []entry) *metaTree {
	root := &metaTree{children: map[string]*metaTree{}}
	for _, e := range entries {
		n := root
		for _, seg := range e.TypePath {
			c := n.children[seg]
			if c == nil {
				c = &metaTree{children: map[string]*metaTree{}}
				n.children[seg] = c
			}
			n = c
		}
		n.fields = append(n.fields, e)
	}
	return root
}

func (n *metaTree) childNames() []string {
	names := make([]string, 0, len(n.children))
	for k := range n.children {
		names = append(names, k)
	}
	sort.Strings(names)
	return names
}

func (n *metaTree) sortedFields() []entry {
	fs := append([]entry(nil), n.fields...)
	sort.Slice(fs, func(i, j int) bool { return fs[i].FieldName < fs[j].FieldName })
	return fs
}

// groupByTypePath groups entries by their dotted package-relative message path
// (e.g. "Config.PositionConfig"), returning the groups and their sorted keys.
// Used by targets that emit one extension per message type (Swift).
func groupByTypePath(entries []entry) (map[string][]entry, []string) {
	groups := map[string][]entry{}
	for _, e := range entries {
		k := strings.Join(e.TypePath, ".")
		groups[k] = append(groups[k], e)
	}
	keys := make([]string, 0, len(groups))
	for k := range groups {
		keys = append(keys, k)
		g := groups[k]
		sort.Slice(g, func(i, j int) bool { return g[i].FieldName < g[j].FieldName })
		groups[k] = g
	}
	sort.Strings(keys)
	return groups, keys
}

// ---- C (nanopb / firmware) ------------------------------------------------
// C has no namespacing, so it keeps only the lookup table + accessor function.

func emitC(schema []schemaField, entries []entry) (string, string) {
	var b strings.Builder
	fmt.Fprintf(&b, "/* %s */\n", doNotEdit)
	b.WriteString("#ifndef MESHTASTIC_FIELD_METADATA_REGISTRY_H\n")
	b.WriteString("#define MESHTASTIC_FIELD_METADATA_REGISTRY_H\n\n")
	b.WriteString("#include <stdbool.h>\n#include <stddef.h>\n#include <stdint.h>\n#include <string.h>\n\n")

	b.WriteString("typedef struct {\n")
	b.WriteString("    const char *message_type;\n")
	b.WriteString("    int field_tag;\n")
	for _, sf := range schema {
		fmt.Fprintf(&b, "    %s %s;\n", cType(sf.Kind), sf.Name)
	}
	b.WriteString("} meshtastic_field_metadata_t;\n\n")

	if len(entries) == 0 {
		b.WriteString("#define MESHTASTIC_FIELD_METADATA_COUNT 0\n\n")
	} else {
		b.WriteString("static const meshtastic_field_metadata_t MESHTASTIC_FIELD_METADATA[] = {\n")
		for _, e := range entries {
			fmt.Fprintf(&b, "    { .message_type = %s, .field_tag = %d", quoteString(e.MessageType), e.Tag)
			for _, sf := range schema {
				if mf, ok := e.fieldValue(sf.Name); ok {
					fmt.Fprintf(&b, ", .%s = %s", sf.Name, cValue(sf.Kind, mf.Value))
				}
			}
			b.WriteString(" },\n")
		}
		b.WriteString("};\n\n")
		fmt.Fprintf(&b, "#define MESHTASTIC_FIELD_METADATA_COUNT %d\n\n", len(entries))
	}

	b.WriteString("static inline const meshtastic_field_metadata_t *\n")
	b.WriteString("meshtastic_field_metadata_get(const char *message_type, int field_tag) {\n")
	if len(entries) == 0 {
		b.WriteString("    (void)message_type; (void)field_tag;\n")
		b.WriteString("    return NULL;\n")
	} else {
		b.WriteString("    for (size_t i = 0; i < MESHTASTIC_FIELD_METADATA_COUNT; i++) {\n")
		b.WriteString("        if (MESHTASTIC_FIELD_METADATA[i].field_tag == field_tag &&\n")
		b.WriteString("            strcmp(MESHTASTIC_FIELD_METADATA[i].message_type, message_type) == 0) {\n")
		b.WriteString("            return &MESHTASTIC_FIELD_METADATA[i];\n")
		b.WriteString("        }\n")
		b.WriteString("    }\n")
		b.WriteString("    return NULL;\n")
	}
	b.WriteString("}\n\n")
	b.WriteString("#endif /* MESHTASTIC_FIELD_METADATA_REGISTRY_H */\n")
	return "meshtastic/field_metadata_registry.h", b.String()
}

func cType(k protoreflect.Kind) string {
	switch k {
	case protoreflect.BoolKind:
		return "bool"
	case protoreflect.DoubleKind, protoreflect.FloatKind:
		return "double"
	case protoreflect.StringKind:
		return "const char *"
	default:
		if isIntKind(k) {
			return "int64_t"
		}
		return "const char *"
	}
}

func cValue(k protoreflect.Kind, v any) string {
	switch k {
	case protoreflect.BoolKind:
		return fmt.Sprintf("%v", v)
	case protoreflect.DoubleKind, protoreflect.FloatKind:
		return strconv.FormatFloat(v.(float64), 'g', -1, 64)
	case protoreflect.StringKind:
		return quoteString(fmt.Sprintf("%v", v))
	default:
		if isIntKind(k) {
			return fmt.Sprintf("%d", v)
		}
		return quoteString(fmt.Sprintf("%v", v))
	}
}

// ---- Python ---------------------------------------------------------------

func emitPython(_ []schemaField, entries []entry) (string, string) {
	var b strings.Builder
	fmt.Fprintf(&b, "# %s\n\n", doNotEdit)
	b.WriteString("from typing import Any, Dict, Optional, Tuple\n\n")

	// Namespaced accessors: FieldMetadataRegistry-style nested classes mirroring
	// the proto structure, e.g. Config.PositionConfig.rx_gpio.
	root := buildTree(entries)
	for _, name := range root.childNames() {
		b.WriteString(pyNode(name, root.children[name], ""))
		b.WriteString("\n")
	}

	// Low-level table + dynamic lookup (escape hatch for generic field walking).
	b.WriteString("# (message_type, field_tag) -> {attribute: value}. Fully-qualified\n")
	b.WriteString("# proto message names, e.g. \"meshtastic.Config.PositionConfig\".\n")
	b.WriteString("_FIELD_METADATA: Dict[Tuple[str, int], Dict[str, Any]] = {\n")
	for _, e := range entries {
		fmt.Fprintf(&b, "    (%s, %d): %s,\n", quoteString(e.MessageType), e.Tag, pyLiteral(e))
	}
	b.WriteString("}\n\n\n")
	b.WriteString("def get(message_type: str, tag: int) -> Optional[Dict[str, Any]]:\n")
	b.WriteString("    \"\"\"Metadata for the field with `tag` on `message_type`, or None.\"\"\"\n")
	b.WriteString("    return _FIELD_METADATA.get((message_type, tag))\n\n\n")
	b.WriteString("def for_type(message_type: str) -> Dict[int, Dict[str, Any]]:\n")
	b.WriteString("    \"\"\"All metadata-annotated fields on `message_type`, keyed by tag.\"\"\"\n")
	b.WriteString("    return {tag: meta for (mt, tag), meta in _FIELD_METADATA.items() if mt == message_type}\n")
	return "meshtastic/field_metadata_registry.py", b.String()
}

func pyNode(name string, n *metaTree, indent string) string {
	var b strings.Builder
	fmt.Fprintf(&b, "%sclass %s:\n", indent, name)
	inner := indent + "    "
	wrote := false
	for _, cn := range n.childNames() {
		b.WriteString(pyNode(cn, n.children[cn], inner))
		wrote = true
	}
	for _, e := range n.sortedFields() {
		fmt.Fprintf(&b, "%s%s = %s\n", inner, e.FieldName, pyLiteral(e))
		wrote = true
	}
	if !wrote {
		b.WriteString(inner + "pass\n")
	}
	return b.String()
}

func pyLiteral(e entry) string {
	parts := make([]string, 0, len(e.Fields))
	for _, f := range e.Fields {
		parts = append(parts, fmt.Sprintf("%s: %s", quoteString(f.Name), pythonValue(f.Value)))
	}
	return "{" + strings.Join(parts, ", ") + "}"
}

func pythonValue(v any) string {
	switch t := v.(type) {
	case bool:
		if t {
			return "True"
		}
		return "False"
	case float64:
		return strconv.FormatFloat(t, 'g', -1, 64)
	case int64:
		return fmt.Sprintf("%d", t)
	default:
		return quoteString(fmt.Sprintf("%v", t))
	}
}

// ---- TypeScript -----------------------------------------------------------

func emitTypeScript(schema []schemaField, entries []entry) (string, string) {
	var b strings.Builder
	fmt.Fprintf(&b, "// %s\n\n", doNotEdit)
	b.WriteString("export interface FieldMetadata {\n")
	for _, sf := range schema {
		fmt.Fprintf(&b, "  %s?: %s;\n", snakeToCamel(sf.Name), tsType(sf.Kind))
	}
	b.WriteString("}\n\n")

	// Namespaced accessors mirroring the proto structure, e.g.
	// Config.PositionConfig.rxGpio.
	root := buildTree(entries)
	for _, name := range root.childNames() {
		fmt.Fprintf(&b, "export const %s = %s;\n\n", name, tsNode(root.children[name], ""))
	}

	// Low-level table + dynamic lookup (escape hatch for generic field walking).
	b.WriteString("// Keyed by `${messageType}#${tag}`, e.g. \"meshtastic.Config.PositionConfig#8\".\n")
	b.WriteString("const REGISTRY: Record<string, FieldMetadata> = {\n")
	for _, e := range entries {
		fmt.Fprintf(&b, "  %s: %s,\n", quoteString(fmt.Sprintf("%s#%d", e.MessageType, e.Tag)), tsLiteral(e))
	}
	b.WriteString("};\n\n")
	b.WriteString("/** Metadata for the field with `tag` on `messageType`, or undefined. */\n")
	b.WriteString("export function get(messageType: string, tag: number): FieldMetadata | undefined {\n")
	b.WriteString("  return REGISTRY[`${messageType}#${tag}`];\n")
	b.WriteString("}\n")
	return "meshtastic/field_metadata_registry.ts", b.String()
}

func tsNode(n *metaTree, indent string) string {
	var b strings.Builder
	b.WriteString("{\n")
	inner := indent + "  "
	for _, name := range n.childNames() {
		fmt.Fprintf(&b, "%s%s: %s,\n", inner, name, tsNode(n.children[name], inner))
	}
	for _, e := range n.sortedFields() {
		fmt.Fprintf(&b, "%s%s: %s as FieldMetadata,\n", inner, snakeToCamel(e.FieldName), tsLiteral(e))
	}
	b.WriteString(indent + "}")
	return b.String()
}

func tsLiteral(e entry) string {
	parts := make([]string, 0, len(e.Fields))
	for _, f := range e.Fields {
		parts = append(parts, fmt.Sprintf("%s: %s", snakeToCamel(f.Name), tsValue(f.Value)))
	}
	return "{ " + strings.Join(parts, ", ") + " }"
}

func tsType(k protoreflect.Kind) string {
	switch k {
	case protoreflect.BoolKind:
		return "boolean"
	case protoreflect.StringKind:
		return "string"
	default:
		return "number"
	}
}

func tsValue(v any) string {
	switch t := v.(type) {
	case bool:
		return fmt.Sprintf("%v", t)
	case float64:
		return strconv.FormatFloat(t, 'g', -1, 64)
	case int64:
		return fmt.Sprintf("%d", t)
	default:
		return quoteString(fmt.Sprintf("%v", t))
	}
}

// ---- Rust (prost) ---------------------------------------------------------

func emitRust(schema []schemaField, entries []entry) (string, string) {
	var b strings.Builder
	fmt.Fprintf(&b, "// %s\n\n", doNotEdit)
	b.WriteString("#[derive(Clone, Copy, Debug, Default, PartialEq)]\n")
	b.WriteString("pub struct FieldMetadata {\n")
	for _, sf := range schema {
		fmt.Fprintf(&b, "    pub %s: Option<%s>,\n", sf.Name, rustType(sf.Kind))
	}
	b.WriteString("}\n\n")

	// Namespaced accessors mirroring the proto structure, e.g.
	// config::position_config::RX_GPIO.
	root := buildTree(entries)
	for _, name := range root.childNames() {
		b.WriteString(rustNode(name, root.children[name], 1, schema))
		b.WriteString("\n")
	}

	// Low-level table + dynamic lookup (escape hatch for generic field walking).
	b.WriteString("/// (fully-qualified message name, field tag, metadata).\n")
	b.WriteString("pub static FIELD_METADATA: &[(&str, i32, FieldMetadata)] = &[\n")
	for _, e := range entries {
		fmt.Fprintf(&b, "    (%s, %d, %s),\n", quoteString(e.MessageType), e.Tag, rustLiteral(schema, e, ""))
	}
	b.WriteString("];\n\n")
	b.WriteString("/// Metadata for the field with `tag` on `message_type`, or `None`.\n")
	b.WriteString("pub fn get(message_type: &str, tag: i32) -> Option<FieldMetadata> {\n")
	b.WriteString("    FIELD_METADATA\n")
	b.WriteString("        .iter()\n")
	b.WriteString("        .find(|(mt, t, _)| *t == tag && *mt == message_type)\n")
	b.WriteString("        .map(|(_, _, meta)| *meta)\n")
	b.WriteString("}\n")
	return "field_metadata_registry.rs", b.String()
}

func rustNode(name string, n *metaTree, depth int, schema []schemaField) string {
	var b strings.Builder
	outer := strings.Repeat("    ", depth-1)
	inner := strings.Repeat("    ", depth)
	fmt.Fprintf(&b, "%spub mod %s {\n", outer, pascalToSnake(name))
	for _, cn := range n.childNames() {
		b.WriteString(rustNode(cn, n.children[cn], depth+1, schema))
	}
	// `super::` * depth reaches the file-root module where FieldMetadata lives.
	prefix := strings.Repeat("super::", depth)
	for _, e := range n.sortedFields() {
		fmt.Fprintf(&b, "%spub const %s: %sFieldMetadata = %s;\n",
			inner, strings.ToUpper(e.FieldName), prefix, rustLiteral(schema, e, prefix))
	}
	fmt.Fprintf(&b, "%s}\n", outer)
	return b.String()
}

func rustLiteral(schema []schemaField, e entry, typePrefix string) string {
	// A `static`/`const` needs a const expression, so emit every attribute
	// explicitly (None when unset) rather than `..Default::default()`.
	parts := make([]string, 0, len(schema))
	for _, sf := range schema {
		if mf, ok := e.fieldValue(sf.Name); ok {
			parts = append(parts, fmt.Sprintf("%s: Some(%s)", sf.Name, decimalFloatValue(mf.Value)))
		} else {
			parts = append(parts, fmt.Sprintf("%s: None", sf.Name))
		}
	}
	return fmt.Sprintf("%sFieldMetadata { %s }", typePrefix, strings.Join(parts, ", "))
}

func rustType(k protoreflect.Kind) string {
	switch k {
	case protoreflect.BoolKind:
		return "bool"
	case protoreflect.DoubleKind, protoreflect.FloatKind:
		return "f64"
	case protoreflect.StringKind:
		return "&'static str"
	default:
		if isIntKind(k) {
			return "i64"
		}
		return "&'static str"
	}
}

// decimalFloatValue renders a scalar value as a literal for Rust and Swift,
// which both require a decimal point on integral floats (Option<f64> / Double?).
func decimalFloatValue(v any) string {
	switch t := v.(type) {
	case bool:
		return fmt.Sprintf("%v", t)
	case float64:
		return decimalFloat(t)
	case int64:
		return fmt.Sprintf("%d", t)
	default:
		return quoteString(fmt.Sprintf("%v", t))
	}
}

// ---- Swift (swift-protobuf) ----------------------------------------------

func emitSwift(schema []schemaField, entries []entry) (string, string) {
	var b strings.Builder
	fmt.Fprintf(&b, "// %s\n\n", doNotEdit)
	b.WriteString("public struct FieldMetadata {\n")
	for _, sf := range schema {
		fmt.Fprintf(&b, "    public var %s: %s? = nil\n", snakeToCamel(sf.Name), swiftType(sf.Kind))
	}
	b.WriteString("}\n\n")

	// Typed accessors as extensions on the real swift-protobuf message types, e.g.
	// `Config.PositionConfig.rxGpio`. Extensions can't add stored properties, so these are
	// computed (returning an immutable struct is cheap).
	groups, keys := groupByTypePath(entries)
	for _, typePath := range keys {
		fmt.Fprintf(&b, "extension %s {\n", typePath)
		for _, e := range groups[typePath] {
			fmt.Fprintf(&b, "    public static var %s: FieldMetadata { %s }\n", snakeToCamel(e.FieldName), swiftLiteral(e))
		}
		b.WriteString("}\n\n")
	}

	// Low-level table + dynamic lookup (escape hatch for generic field walking).
	b.WriteString("public enum FieldMetadataRegistry {\n")
	b.WriteString("    // Keyed by \"\\(messageType)#\\(tag)\".\n")
	b.WriteString("    static let registry: [String: FieldMetadata] = [\n")
	for _, e := range entries {
		fmt.Fprintf(&b, "        %s: %s,\n", quoteString(fmt.Sprintf("%s#%d", e.MessageType, e.Tag)), swiftLiteral(e))
	}
	b.WriteString("    ]\n\n")
	b.WriteString("    /// Metadata for the field with `tag` on `messageType`, or nil.\n")
	b.WriteString("    public static func get(_ messageType: String, tag: Int) -> FieldMetadata? {\n")
	b.WriteString("        return registry[\"\\(messageType)#\\(tag)\"]\n")
	b.WriteString("    }\n")
	b.WriteString("}\n")
	return "FieldMetadataRegistry.swift", b.String()
}

func swiftLiteral(e entry) string {
	parts := make([]string, 0, len(e.Fields))
	for _, f := range e.Fields {
		parts = append(parts, fmt.Sprintf("%s: %s", snakeToCamel(f.Name), decimalFloatValue(f.Value)))
	}
	return "FieldMetadata(" + strings.Join(parts, ", ") + ")"
}

func swiftType(k protoreflect.Kind) string {
	switch k {
	case protoreflect.BoolKind:
		return "Bool"
	case protoreflect.DoubleKind, protoreflect.FloatKind:
		return "Double"
	case protoreflect.StringKind:
		return "String"
	default:
		if isIntKind(k) {
			return "Int64"
		}
		return "String"
	}
}

func isIntKind(k protoreflect.Kind) bool {
	switch k {
	case protoreflect.Int32Kind, protoreflect.Int64Kind, protoreflect.Uint32Kind,
		protoreflect.Uint64Kind, protoreflect.Sint32Kind, protoreflect.Sint64Kind,
		protoreflect.Fixed32Kind, protoreflect.Fixed64Kind, protoreflect.Sfixed32Kind,
		protoreflect.Sfixed64Kind:
		return true
	}
	return false
}
