// kotlinx.serialization serializers for every type in `protobufs`, published beside it as
// `org.meshtastic:protobufs-serialization` so the main artifact carries no serialization runtime.
// Generated by KotlinxSerializersHandler in buildSrc from the same protos; see its KDoc for the
// shape (proto3 JSON's), and reached as `LocalConfig.serializer()`.
plugins {
    kotlin("multiplatform")
    id("com.android.kotlin.multiplatform.library")
    id("com.squareup.wire")
    id("com.vanniktech.maven.publish")
}

group = rootProject.group
version = rootProject.version

@OptIn(org.jetbrains.kotlin.gradle.ExperimentalWasmDsl::class)
kotlin {
    android {
        namespace = "org.meshtastic.proto.serialization"
        compileSdk = 37
        minSdk = 24
    }
    jvm()
    js {
        browser()
        nodejs()
    }
    wasmJs {
        browser()
    }
    wasmWasi {
        nodejs()
    }
    macosArm64()
    linuxX64()
    linuxArm64()
    mingwX64()
    iosX64()
    iosArm64()
    iosSimulatorArm64()
    tvosArm64()
    tvosSimulatorArm64()

    sourceSets {
        commonMain {
            dependencies {
                api(project(":"))
                api("org.jetbrains.kotlinx:kotlinx-serialization-core:1.11.0")
            }
        }
    }
}

tasks.withType<Jar>().configureEach {
    from(rootProject.layout.projectDirectory.file("../../LICENSE"))
}

// The protos the root project syncs; this project generates serializers only, against its types.
wire {
    sourcePath {
        srcDir(rootProject.layout.buildDirectory.dir("protos"))
        include("meshtastic/**/*.proto")
        include("nanopb.proto")
    }
    custom {
        schemaHandlerFactoryClass = "org.meshtastic.proto.build.KotlinxSerializersHandlerFactory"
        out = "build/generated/source/wire-kotlinx-serializers"
    }
}

// Class file 55, as the root project pins it, so a JDK 21 consumer can load it.
tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinJvmCompile>().configureEach {
    compilerOptions {
        jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_11)
        freeCompilerArgs.add("-Xjdk-release=11")
    }
}

afterEvaluate {
    tasks.matching { it.name.startsWith("generate") && it.name.endsWith("Protos") }.configureEach {
        dependsOn(":syncProtos", ":syncNanopb")
    }
}

mavenPublishing {
    publishToMavenCentral(automaticRelease = true)
    if (providers.gradleProperty("signingInMemoryKey").isPresent) {
        signAllPublications()
    }

    pom {
        name.set("Meshtastic Protobufs Serialization")
        description.set("kotlinx.serialization serializers for the Meshtastic protobuf models, in proto3 JSON's shape.")
        inceptionYear.set("2026")
        url.set("https://github.com/meshtastic/protobufs")
        licenses {
            license {
                name.set("GNU General Public License, Version 3.0")
                url.set("https://www.gnu.org/licenses/gpl-3.0.html")
                distribution.set("repo")
            }
        }
        developers {
            developer {
                id.set("meshtastic")
                name.set("Meshtastic")
                url.set("https://meshtastic.org")
            }
        }
        scm {
            url.set("https://github.com/meshtastic/protobufs")
            connection.set("scm:git:git://github.com/meshtastic/protobufs.git")
            developerConnection.set("scm:git:ssh://git@github.com/meshtastic/protobufs.git")
        }
    }
}
