name: pull-request

permissions:
  contents: read

on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Buf
        uses: bufbuild/buf-setup-action@v1.30.0
        with:
          github_token: ${{ github.token }}

      - name: Lint
        uses: bufbuild/buf-lint-action@v1.1.1

      - name: Push to schema registry
        uses: bufbuild/buf-push-action@v1.2.0
        if: ${{ github.event_name != 'pull_request_target' && github.event_name != 'pull_request' }}
        with:
          buf_token: ${{ secrets.BUF_TOKEN }}
          draft: ${{ github.ref_name != 'master'}}
